# Generated by Django 6.0.1 on 2026-01-24 13:11

import c2b.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("c2b", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="c2btransaction",
            new_name="c2b_c2btran_shortco_c3750c_idx",
            old_name="c2b_c2btra_shortco_5a6a0e_idx",
        ),
        migrations.RenameIndex(
            model_name="c2btransaction",
            new_name="c2b_c2btran_status_df01b8_idx",
            old_name="c2b_c2btra_status_4cdb03_idx",
        ),
        migrations.RenameIndex(
            model_name="shortcode",
            new_name="c2b_shortco_shortco_9b653e_idx",
            old_name="c2b_shortco_shortcode_2e1d44_idx",
        ),
        migrations.RenameIndex(
            model_name="shortcode",
            new_name="c2b_shortco_is_acti_056c9a_idx",
            old_name="c2b_shortco_is_activ_9cd7f2_idx",
        ),
        migrations.AlterField(
            model_name="shortcode",
            name="webhook_token",
            field=models.CharField(
                default=c2b.models._generate_webhook_token,
                editable=False,
                max_length=64,
            ),
        ),
    ]
